name: Bug report
description: Report a reproducible bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue.

        Please provide enough detail for reproduction.
        
        This template is only for code or functional product issues.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce it?
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version / commit
      description: Branch name, commit hash, or release version.
      placeholder: e.g. main @ abc123

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, browser, Node version, etc.
      placeholder: |
        - OS:
        - Browser:
        - Node:

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or screenshots
      description: Paste error output or attach screenshots.
      render: shell
