name: Feature request
description: Suggest an idea or enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement.
        
        This template is only for functional product enhancements.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: A clear description of the pain point.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to happen?
      placeholder: Describe your preferred solution.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you considered?

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Mockups, examples, constraints, or references.
